image: node:latest

before_script:
  - yarn install

cache:
  paths:
    - node_modules/
    - .next/cache/

pages:
  script:
    - yarn install
    - yarn build
    - mv out public
  artifacts:
    paths:
      - public
  only:
    - main
